name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]        
    
    runs-on: $matrix.os
    services:
      mssql1:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: MyTestPassword
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
        
    steps:
      - name: Hello
        run: |
          echo "Hello World, Docker"
